---
- name: Ensure project directory exists
  file: path=/home/vagrant/repos/magento2 state=directory

- name: Create project
  shell: git clone https://<user>:<password>@<GIT repo> . 
  args:
    chdir: /home/vagrant/repos/magento2
    creates: /home/vagrant/repos/magento2/composer.json
- name: Composer install
  shell: composer install
  args:
    chdir: /home/vagrant/repos/magento2
